language: java
jdk: oraclejdk8
script:
  - mvn clean install package validate -e

  #- cd Authentication
  #- mvn clean install
  ##- nohup mvn exec:java -Dexec.mainClass=test.Main -Dexec.args="dev"

  #- cd ../Maintenance
  #- mvn clean install
  ##- nohup mvn exec:java -Dexec.mainClass=test.Main -Dexec.args="dev"

  #- cd ../Valet
  #- mvn clean install
  ##- nohup mvn exec:java -Dexec.mainClass=test.Main -Dexec.args="dev"

  #- cd ../Vehicle
  #- mvn clean install
  ##- nohup mvn exec:java -Dexec.mainClass=test.Main -Dexec.args="dev"